# Generated by Django 5.2.14 on 2026-05-19 02:59

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_role_rolepermission_userrole_and_more"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("card", "Card"),
                            ("bank_transfer", "Bank Transfer"),
                            ("wallet", "Wallet"),
                        ],
                        default="card",
                        max_length=50,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("paypal", "PayPal"),
                            ("manual", "Manual"),
                        ],
                        default="stripe",
                        max_length=50,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "stripe_payment_method_id",
                    models.CharField(blank=True, max_length=255),
                ),
                ("stripe_customer_id", models.CharField(blank=True, max_length=255)),
                ("last_four", models.CharField(blank=True, max_length=4)),
                ("card_brand", models.CharField(blank=True, max_length=50)),
                (
                    "expiry_month",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "expiry_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to="core.customer",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Method",
                "verbose_name_plural": "Payment Methods",
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "gateway",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("paypal", "PayPal"),
                            ("manual", "Manual"),
                        ],
                        default="stripe",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("authorized", "Authorized"),
                            ("paid", "Paid"),
                            ("partially_paid", "Partially Paid"),
                            ("refunded", "Refunded"),
                            ("partially_refunded", "Partially Refunded"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, max_length=255),
                ),
                ("stripe_charge_id", models.CharField(blank=True, max_length=255)),
                ("gateway_response", models.JSONField(default=dict)),
                ("error_code", models.CharField(blank=True, max_length=255)),
                ("error_message", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_transactions",
                        to="orders.order",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="payments.paymentmethod",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Transaction",
                "verbose_name_plural": "Payment Transactions",
            },
        ),
        migrations.CreateModel(
            name="PaymentRefund",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("duplicate", "Duplicate"),
                            ("fraudulent", "Fraudulent"),
                            ("requested_by_customer", "Requested by Customer"),
                            ("other", "Other"),
                        ],
                        default="requested_by_customer",
                        max_length=50,
                    ),
                ),
                ("stripe_refund_id", models.CharField(blank=True, max_length=255)),
                ("gateway_response", models.JSONField(default=dict)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refunds",
                        to="payments.paymenttransaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Refund",
                "verbose_name_plural": "Payment Refunds",
            },
        ),
        migrations.CreateModel(
            name="StripeWebhookEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("stripe_event_id", models.CharField(max_length=255, unique=True)),
                ("event_type", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                            ("ignored", "Ignored"),
                        ],
                        default="received",
                        max_length=50,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                ("error", models.TextField(blank=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Stripe Webhook Event",
                "verbose_name_plural": "Stripe Webhook Events",
                "indexes": [
                    models.Index(
                        fields=["stripe_event_id"],
                        name="payments_st_stripe__a444ea_idx",
                    ),
                    models.Index(
                        fields=["event_type"], name="payments_st_event_t_802e5e_idx"
                    ),
                    models.Index(
                        fields=["status"], name="payments_st_status_2b0711_idx"
                    ),
                    models.Index(
                        fields=["received_at"], name="payments_st_receive_34cf1c_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="paymentmethod",
            index=models.Index(
                fields=["customer"], name="payments_pa_custome_437c8f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentmethod",
            index=models.Index(
                fields=["stripe_payment_method_id"],
                name="payments_pa_stripe__ffc15c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentmethod",
            index=models.Index(
                fields=["stripe_customer_id"], name="payments_pa_stripe__a175e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentmethod",
            index=models.Index(
                fields=["is_default"], name="payments_pa_is_defa_9c26a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentmethod",
            index=models.Index(
                fields=["provider"], name="payments_pa_provide_cd2380_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(fields=["order"], name="payments_pa_order_i_d65105_idx"),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(fields=["status"], name="payments_pa_status_b6726a_idx"),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["stripe_payment_intent_id"],
                name="payments_pa_stripe__3365e3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["stripe_charge_id"], name="payments_pa_stripe__3031ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["gateway"], name="payments_pa_gateway_e74888_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["created_at"], name="payments_pa_created_a246c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentrefund",
            index=models.Index(
                fields=["transaction"], name="payments_pa_transac_3359ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentrefund",
            index=models.Index(fields=["status"], name="payments_pa_status_b3312f_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentrefund",
            index=models.Index(
                fields=["stripe_refund_id"], name="payments_pa_stripe__5345b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentrefund",
            index=models.Index(
                fields=["created_at"], name="payments_pa_created_10d7cb_idx"
            ),
        ),
    ]
