# Generated by Django 5.2.14 on 2026-08-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_role_rolepermission_userrole_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="stripe_customer_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
