# Generated by Django 5.2.14 on 2026-05-19 17:19

import django.db.models.deletion
import outbound_webhooks.models.webhook_endpoint
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WebhookEndpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "secret",
                    models.CharField(
                        default=outbound_webhooks.models.webhook_endpoint._default_secret,
                        max_length=64,
                    ),
                ),
                ("events", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("failure_count", models.PositiveIntegerField(default=0)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Webhook Endpoint",
                "verbose_name_plural": "Webhook Endpoints",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="outbound_we_is_acti_84bf72_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.CharField(max_length=100)),
                ("payload", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "response_status_code",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("response_body", models.TextField(blank=True, null=True)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="outbound_webhooks.webhookendpoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Delivery",
                "verbose_name_plural": "Webhook Deliveries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="outbound_we_status_4a6291_idx"
                    ),
                    models.Index(
                        fields=["endpoint", "created_at"],
                        name="outbound_we_endpoin_06ec71_idx",
                    ),
                ],
            },
        ),
    ]
