# Generated by Django 5.2.14 on 2026-05-19 17:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cart", "0002_alter_cartitem_options_and_more"),
        ("core", "0002_role_rolepermission_userrole_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GiftCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "initial_balance",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_gift_cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issued_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gift_cards",
                        to="core.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gift Card",
                "verbose_name_plural": "Gift Cards",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CartGiftCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount_applied",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applied_gift_cards",
                        to="cart.cart",
                    ),
                ),
                (
                    "gift_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gift_cards.giftcard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cart Gift Card",
                "verbose_name_plural": "Cart Gift Cards",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GiftCardTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("issued", "Issued"),
                            ("redeemed", "Redeemed"),
                            ("refunded", "Refunded"),
                            ("expired", "Expired"),
                            ("voided", "Voided"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order_id", models.UUIDField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gift_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="gift_cards.giftcard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gift Card Transaction",
                "verbose_name_plural": "Gift Card Transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="giftcard",
            index=models.Index(fields=["code"], name="gift_cards__code_9fe396_idx"),
        ),
        migrations.AddIndex(
            model_name="giftcard",
            index=models.Index(
                fields=["is_active"], name="gift_cards__is_acti_11afe8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cartgiftcard",
            unique_together={("cart", "gift_card")},
        ),
        migrations.AddIndex(
            model_name="giftcardtransaction",
            index=models.Index(
                fields=["gift_card"], name="gift_cards__gift_ca_bf736a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="giftcardtransaction",
            index=models.Index(
                fields=["created_at"], name="gift_cards__created_0c5b8f_idx"
            ),
        ),
    ]
