# Generated by Django 5.2.14 on 2026-05-19 17:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
        ("core", "0002_role_rolepermission_userrole_and_more"),
        ("products", "0002_product_products_pr_slug_3edc0c_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartitem",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Cart Item",
                "verbose_name_plural": "Cart Items",
            },
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(
                fields=["session_key"], name="cart_cart_session_5e1af5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(
                fields=["customer"], name="cart_cart_custome_22ccdd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(
                fields=["is_active"], name="cart_cart_is_acti_96bd76_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(
                fields=["expires_at"], name="cart_cart_expires_8a239f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(
                fields=["created_at"], name="cart_cart_created_981ed1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(
                fields=["updated_at"], name="cart_cart_updated_c46eb6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(
                fields=["customer", "is_active"], name="cart_cart_custome_31bf1b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(
                fields=["session_key", "is_active"], name="cart_cart_session_3c25be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(
                fields=["expires_at", "is_active"], name="cart_cart_expires_42e875_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(fields=["cart"], name="cart_cartit_cart_id_4fb076_idx"),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(
                fields=["product_variant"], name="cart_cartit_product_982ec9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(
                fields=["created_at"], name="cart_cartit_created_941681_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(
                fields=["updated_at"], name="cart_cartit_updated_339dfa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(
                fields=["cart", "product_variant"],
                name="cart_cartit_cart_id_52ca2b_idx",
            ),
        ),
    ]
